### ISSUE TITLE
Feature request: Switchports and SVI interfaces

### ISSUE THREAD

**Issue by andreasbaekdahl** [CiscoDevNet/terraform-provider-sdwan#109]
Support for feature templates of type "VPN Interface SVI" and "Switch Port" is needed to support devices in the C1100 series routers.

**Comment by andreasbaekdahl** [comment]
Is this something that is being looked into? We have an upcoming deployment where switchports and SVI is needed.

**Comment by lap-wingmen** [comment]
I am also really interested - let us know a timeline please.

**Comment by danischm** [comment]
We have put this into our backlog, but have to prioritize a few other things and therefore cannot commit to an ETA at this point. However, we are happy to help and support with outside contributions.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/6c8ed6d5c0f4cc0c4ad656a513a2172198b29aa9

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/528267fe3c909e600a555d73c5ba3f269b967816

**Comment by danischm** [comment]
Added in 0.3.4 release.
