### ISSUE TITLE
Missing support for Manage Custom Preferences and Prefix Lists in Hub Preferences (Centralized Policy > Hub and Spoke Topology)

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#112]
Resource "sdwan_hub_and_spoke_topology_policy_definition" doesn't have support for "Manage Custom Preferences and Prefix Lists" in "Hub Preferences" (Centralized Policy > Hub and Spoke Topology).

We should be able to 

1. set Bool value for >> All hubs are equal (All Spokes Sites connect to all Hubs)
2. set Bool value for >> Advertise Hub TLOCs and select TLOC list
3. When "All hubs are equal (All Spokes Sites connect to all Hubs)" is unset, it should allow setting the priority for the list of Hubs.
4. Able to map a Prefix list for each of the Spoke to Hub association

in Vmanage GUI

<img width="730" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/824b44a5-e500-485f-817e-3e3c374b8da8">

Missing Options (everything configurable in the below path in vManage GUI)

<img width="1382" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/dbb72c11-2dcd-4fb1-b3d4-c704a3cdc8cb">

<img width="1232" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/ed88c342-1a7b-4bd5-9bda-3297223746e0">

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/2922848495deea7d3cccd63ec93b65ca49ecabcb

**Comment by danischm** [comment]
Added in v0.3.8 .
