### ISSUE TITLE
base_action for sequences not accepted by sdwan_traffic_data_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#118]
The sequences of the sdwan_traffic_data_policy_definition should allow defining base_action as documented below.
However, we see that the plan file doesn't generate value for this field.

[base_action](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/traffic_data_policy_definition#base_action) (String) Base action, either accept or drop
Choices: accept, drop

For Reference: A similar issue was created recently >> https://github.com/CiscoDevNet/terraform-provider-sdwan/issues/114
Please see, if these are similar and handle accordingly.

**Comment by danischm** [comment]
This should be fixed from 0.2.11 release onwards.

**Comment by rrahimm** [comment]
Hi Dan

i tested this and it worked in the latest release.
