### ISSUE TITLE
Port and Protocol not accepting multivalue in sdwan_traffic_data_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#119]
When defining [sequences.match_entries](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/traffic_data_policy_definition#nested-schema-for-sequencesmatch_entries) in sdwan_traffic_data_policy_definition, the fields **protocol, sourcePort, destinationPort** should support multiple values.

However, the provider takes only one value (as documented). We would like to get this field to support multiple values. This could either be the same way as in GUI (values separated by a comma or as a list. The first one ensure reverse compatibility)

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/8e7e4a1d-8678-48cf-83e7-7f7c5fd3b8b7)
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/b3700814-dd8c-4b73-b89d-f354a49912ae)
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/6d3644c6-260d-4285-a906-aa292a5ff9e2)

GUI showing these as multivalue fields.
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/531a6e6d-6cda-4462-9e6c-595a9cdd2477)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/d7e9a04a9f6ecfde8278937b8a6a718a4ceaac23

**Comment by danischm** [comment]
Fixed in 0.3.0 release.

**Comment by rrahimm** [comment]
tested
