### ISSUE TITLE
Local and restrict options are unavailable in sdwan_traffic_data_policy_definition for set_parameters

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#120]
The sdwan_traffic_data_policy_definition doesn't allow defining the local and restrict options that are part of the Centralized Policy >Data Policy > Service Chaining > Service.

it's not documented aswell.

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/60c1ce09-b130-48c9-98b5-0e1cac942a60)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/d7e9a04a9f6ecfde8278937b8a6a718a4ceaac23

**Comment by danischm** [comment]
Fixed in 0.3.0 release.

**Comment by rrahimm** [comment]
tested

minor issue found.

when set to false, they still remain as true. able to set to false, only when the respective parameter is completely taken off the configuration.
