### ISSUE TITLE
Support for feature templates: Cellular controller and VPN Interface Cellular

### ISSUE THREAD

**Issue by andreasbaekdahl** [CiscoDevNet/terraform-provider-sdwan#124]
Please add support for resources for the following feature template types: 

- Cellular controller
- VPN Interface Cellular

**Comment by andreasbaekdahl** [comment]
Is this something that is being looked into? We have an upcoming deployment where cellular support is needed.

**Comment by lap-wingmen** [comment]
I am also really interested - let us know a timeline please.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/pull/181

**Comment by danischm** [comment]
Added in v0.3.7 release.
