### ISSUE TITLE
unable to set export_to_vpn_list_id and version in sdwan_custom_control_topology_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#125]
when trying to set exportTo in sdwan_custom_control_topology_policy_definition [sequences.action_entries](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/custom_control_topology_policy_definition#nested-schema-for-sequencesaction_entries), the apply fails with the below error.
│ Failed to configure object (POST), got error: HTTP Request failed: StatusCode 400, {"error":{"type":"error","message":"Invalid policy","details":"SeqID 1: Field missing from export action","code":"POLICY0004"}}

                  + {
                      + export_to_vpn_list_id      = (known after apply)
                      + export_to_vpn_list_version = (known after apply)
                      + type                       = "exportTo"
                    },

Plan
` + resource "sdwan_custom_control_topology_policy_definition" "custom_control_topology_policy_definition" {
      + default_action = "accept"
      + description    = "CCT_DEFINITION_TEST1"
      + id             = (known after apply)
      + name           = "CCT_DEFINITION_TEST1"
      + sequences      = [
          + {
              + action_entries = [
                  + {
                      + set_parameters = [
                          + {
                              + community = "100:1000"
                              + type      = "community"
                            },
                          + {
                              + community_additive = true
                              + type               = "communityAdditive"
                            },
                          + {
                              + preference = 48
                              + type       = "preference"
                            },
                          + {
                              + omp_tag = 88
                              + type    = "ompTag"
                            },
                          + {
                              + tloc_action = "strict"
                              + type        = "tlocAction"
                            },
                          + {
                              + tloc_color         = "custom2"
                              + tloc_encapsulation = "ipsec"
                              + tloc_ip            = "1.2.5.9"
                              + type               = "tloc"
                            },
                          + {
                              + tloc_list_id      = "25a11085-0833-4c14-86ec-b76d6727cca4"
                              + tloc_list_version = 0
                              + type              = "tlocList"
                            },
                          + {
                              + service_tloc_color         = "custom1"
                              + service_tloc_encapsulation = "ipsec"
                              + service_tloc_ip            = "3.4.5.6"
                              + service_type               = "netsvc1"
                              + service_vpn_id             = 62
                              + type                       = "service"
                            },
                        ]
                      + type           = "set"
                    },
                  + {
                      + export_to_vpn_list_id      = (known after apply)
                      + export_to_vpn_list_version = (known after apply)
                      + type                       = "exportTo"
                    },
                ]
              + id             = 1
              + ip_type        = "ipv4"
              + match_entries  = [
                  + {
                      + color_list_id      = (known after apply)
                      + color_list_version = (known after apply)
                      + type               = "colorList"
                    },
                  + {
                      + community_list_id      = (known after apply)
                      + community_list_version = (known after apply)
                      + type                   = "community"
                    },
                  + {
                      + omp_tag = 65
                      + type    = "ompTag"
                    },
                  + {
                      + expanded_community_list_id      = (known after apply)
                      + expanded_community_list_version = (known after apply)
                      + type                            = "expandedCommunity"
                    },
                  + {
                      + preference = 45
                      + type       = "preference"
                    },
                  + {
                      + originator = "10.10.20.30"
                      + type       = "originator"
                    },
                  + {
                      + site_list_id      = (known after apply)
                      + site_list_version = (known after apply)
                      + type              = "siteList"
                    },
                  + {
                      + site_id = 6789056
                      + type    = "siteId"
                    },
                  + {
                      + path_type = "direct-path"
                      + type      = "pathType"
                    },
                  + {
                      + tloc_list_id      = (known after apply)
                      + tloc_list_version = (known after apply)
                      + type              = "tlocList"
                    },
                  + {
                      + type             = "vpnList"
                      + vpn_list_id      = (known after apply)
                      + vpn_list_version = (known after apply)
                    },
                  + {
                      + prefix_list_id      = (known after apply)
                      + prefix_list_version = (known after apply)
                      + type                = "prefixList"
                    },
                  + {
                      + tloc_color         = "custom1"
                      + tloc_encapsulation = "ipsec"
                      + tloc_ip            = "10.10.33.67"
                      + type               = "tloc"
                    },
                ]
              + name           = "rule1"
              + type           = "route"
            },
          + {
              + action_entries = [
                  + {
                      + set_parameters = [
                          + {
                              + omp_tag = 89
                              + type    = "ompTag"
                            },
                          + {
                              + preference = 49
                              + type       = "preference"
                            },
                        ]
                      + type           = "set"
                    },
                ]
              + id             = 2
              + ip_type        = "ipv4"
              + match_entries  = [
                  + {
                      + carrier = "carrier1"
                      + type    = "carrier"
                    },
                  + {
                      + color_list_id      = (known after apply)
                      + color_list_version = (known after apply)
                      + type               = "colorList"
                    },
                  + {
                      + domain_id = 567
                      + type      = "domainId"
                    },
                  + {
                      + group_id = 678
                      + type     = "groupId"
                    },
                  + {
                      + omp_tag = 77
                      + type    = "ompTag"
                    },
                  + {
                      + originator = "12.13.14.15"
                      + type       = "originator"
                    },
                  + {
                      + preference = 88
                      + type       = "preference"
                    },
                  + {
                      + site_list_id      = (known after apply)
                      + site_list_version = (known after apply)
                      + type              = "siteList"
                    },
                  + {
                      + site_id = 6789056
                      + type    = "siteId"
                    },
                  + {
                      + tloc_list_id      = (known after apply)
                      + tloc_list_version = (known after apply)
                      + type              = "tlocList"
                    },
                  + {
                      + tloc_color         = "custom1"
                      + tloc_encapsulation = "ipsec"
                      + tloc_ip            = "10.10.33.67"
                      + type               = "tloc"
                    },
                ]
              + name           = "rule2"
              + type           = "tloc"
            },
        ]
      + version        = (known after apply)
    }`

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/8ea89eb171f111e6e10711bce46b5d9af49bf5eb

**Comment by danischm** [comment]
Fixed in 0.3.1 release.

**Comment by rrahimm** [comment]
tested
