### ISSUE TITLE
additional capability for secure internet gateway on sdwan_traffic_data_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#133]
we need the capability to configure "Fallback to Routing" option under "secure internet gateway" configuration in sdwan_traffic_data_policy_definition

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/833af087-f21b-4c2b-93c5-6e51b047839d)

**Comment by danischm** [comment]
This should already be there (https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/traffic_data_policy_definition#fallback_to_routing), though you need a separate action entry for that.

**Comment by danischm** [comment]
can this be closed?

**Comment by rrahimm** [comment]
Hello @danischm 

The fallback_to_routing stays enabled even if the value is set to false. In other words, presence of (type = "fallbackToRouting") always keeps the setting enabled.

              ~ action_entries = [
                  ~ {
                      + fallback_to_routing = false
                      + type                = "fallbackToRouting"

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/3a0d9b62-54dc-44cb-971c-445c54c6b7e3)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/733520754a81882f90c2996ecec9ecdc7bc6a5fa

**Comment by rrahimm** [comment]
This is working and tested.
