### ISSUE TITLE
additional capability for "AppQoE Optimization" on sdwan_traffic_data_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#134]
we need the capability to configure "Service Node Group" option under "AppQoE Optimization" configuration in sdwan_traffic_data_policy_definition

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/00699fc6-2429-4f58-bf02-1c26d43be074)

**Comment by danischm** [comment]
This should already be there (https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/traffic_data_policy_definition#service_node_group), though you need a separate action entry for that.

**Comment by danischm** [comment]
can this be closed?

**Comment by rrahimm** [comment]
Hello @danischm 

We see that even if we set the dre_optimization to false, it remains enabled. It turns out that the value of true or false, doesnt make a difference. As long as the type is there, the option gets enabled.

If i remove the respective option completely out of the configuration data, then it doesnt get enabled. 

                      + tcp_optimization = true
                      _ type             = "tcpOptimization"
                    },
                  + {
                      + dre_optimization = false
                      + type             = "dreOptimization"
                    },
                  + {
                      + service_node_group = "SNG-APPQOE5"
                      + type               = "serviceNodeGroup"
                    },
                    
 
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/4d3e5033-edc3-483c-a695-2156294b6612)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/733520754a81882f90c2996ecec9ecdc7bc6a5fa

**Comment by danischm** [comment]
This should be fixed in the latest release, can you confirm?

**Comment by danischm** [comment]
Thanks for verifying, will look into it!

**Comment by danischm** [comment]
This is indeed the case. However the provider is setting the payload correctly, but as soon as an `action_entry` with type `dreOptimization` is included, the UI shows this feature as enabled. In this case we should make sure we do not add such an `action_entry` to the list in case we don't want it to be enabled.

**Comment by rrahimm** [comment]
Thanks @danischm 

i will try to make the Terraform module consider only true as input.
