### ISSUE TITLE
redirect_dns_type in sdwan_traffic_data_policy_definition should also support ip_address as a value

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#135]
we see that the redirect_dns_type value is being set to value of [redirect_dns_address](https://registry.terraform.io/providers/CiscoDevNet/sdwan/0.2.7/docs/resources/traffic_data_policy_definition#redirect_dns_address) and thus tfplan keeps reporing pending configurations.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/cc41ec54efac4f51164e3796098b7cd7cab21f41

**Comment by danischm** [comment]
Fixed in 0.3.1 release.
