### ISSUE TITLE
backup_sla_preferred_color should accept multivalue in sdwan_application_aware_routing_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#141]
The field backup_sla_preferred_color is a multi-select field in SDWAN GUI.

<img width="667" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/c89535f0-0939-40d8-927e-52d4f7f99b58">

**Comment by seconroy** [comment]
backup_sla_preferred_color supports a single value or multiple values separated by spaces, The documentation will be updated to make this more clear.

**Comment by rrahimm** [comment]
tested
