### ISSUE TITLE
preferred_color should support multivalue in sdwan_application_aware_routing_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#142]
preferred_color should support multivalue in [sequences.action_entries.sla_class_parameters](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/application_aware_routing_policy_definition#nested-schema-for-sequencesaction_entriessla_class_parameters)

**Comment by seconroy** [comment]
preferred_color supports a single value or multiple values separated by spaces, The documentation will be updated to make this more clear.

**Comment by rrahimm** [comment]
Tested
