### ISSUE TITLE
missing Voice vlan in sdwan_switchport_feature_template 

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#149]
we see that the Voice Vlan option is missing

we also see that an option called "dot1x_voice_vlan" exists, but doesn't exist in vManage. Possibly a typo error.

**Comment by danischm** [comment]
What specifically is the request here? Voice vlan ID can be configured per interface.

**Comment by rrahimm** [comment]
i only see [dot1x_voice_vlan](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/switchport_feature_template#dot1x_voice_vlan)

is it a typo error in provider ?

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/dc05bd80-1ebe-4d1d-998f-51c1c3df4d5e)

**Comment by danischm** [comment]
You mean why it is called `dot1x_voice_vlan` instead of `voice_vlan`? It is derived from the vManage schema:
```
                {
                    "dataPath": [
                        "dot1x"
                    ], 
                    "dataType": {
                        "max": 4094, 
                        "min": 1, 
                        "type": "number"
                    }, 
                    "defaultOption": "ignore", 
                    "description": "Voice VLAN ID", 
                    "details": "Configure Voice Vlan", 
                    "key": "voice-vlan", 
                    "objectType": "object", 
                    "optionType": [
                        "constant", 
                        "variable", 
                        "ignore"
                    ]
                },
```
If this is not correct we can adjust the name in the Terraform resource.

**Comment by rrahimm** [comment]
Hi @danischm 

yes, that was the concern. I did some analysis and found that there is no Voice_vlan option under dot_1x, so calling it as dot1x_voice_vlan may not be right !!!

but, to my surprise, that's how the API also calls it in the payload.

It's a simple update to the Terraform Module that I can make and let this work.

or do you think, this should be renamed accordingly in Provider?

**Comment by danischm** [comment]
Renamed: https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/297bf001d2910c5e4966488ee7373a1f532c413a

**Comment by danischm** [comment]
Renamed in v0.3.6.

**Comment by rrahimm** [comment]
PR Created >> https://github.com/netascode/terraform-sdwan-nac-sdwan/pull/19
