### ISSUE TITLE
BGP ipv6-unicast address family

### ISSUE THREAD

**Issue by juchowan** [CiscoDevNet/terraform-provider-sdwan#155]
For ipv6-unicast family use only ipv6-aggregate-address and ipv6-network. For ipv4-unicast only aggregate-address and network as in here:

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/ff9e6bd4-d78e-4857-a33f-2e32921e296e)

What's happening now is that at the moment we configure ipv6 network or aggregate, both types are configured in both families:

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/51c2f50b-69c6-4bcd-86a6-99b3b649296c)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/474fe700621f48f5421d52d056fb7af7b41729d6
