### ISSUE TITLE
OSPF area types

### ISSUE THREAD

**Issue by juchowan** [CiscoDevNet/terraform-provider-sdwan#156]
Areas should use only nssa or only stub, not both at the same time. Currently what happens for 0-stub and 1-nssa

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/7a950732-9ffe-488e-90e9-c822109f1fe8)

This is with no-summary:
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/62b7217d-31f0-48f4-9537-25bb42240d1d)

Should look like this:
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/e7d1a7f1-f766-4f2f-9339-a3ca376e966b)

With no-summary:
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/90ffa3d9-bf2b-45e0-92d7-5d61e425342b)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/2466bf10e565e856b058f0bcb808c97f28cedee2
