### ISSUE TITLE
Secure Internet Gateway templates - service zscaler vs umbrella

### ISSUE THREAD

**Issue by juchowan** [CiscoDevNet/terraform-provider-sdwan#160]
For service itshould only include either zscaler or umbrella, not both. Currently for zscaler:

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/4d65f03d-63b2-4b02-91c7-321cae91378a)

Should be for zscaler:
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/cf2e94b1-bbf7-4e3c-8298-f0016026c735)

Should be for umbrella:
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/9090d8aa-ffa0-4b67-a4eb-2f6a36825fde)

**Comment by juchowan** [comment]
same for generic, it shouldn't include umbrella and zscaler

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/3c2618e3953ed1b169a26f4abed8c30777ec58f3

**Comment by danischm** [comment]
This should be fixed in the v0.3.6 release, can you confirm?

**Comment by juchowan** [comment]
for interfaces -> ike -> authentication-type -> need to ignore pre-shared-key, when pre-shared-key-dynamic is used (for zscaler and umbrella type)

**Comment by juchowan** [comment]
for interfaces need to ignore ike and ipsec if not set

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/52506e9a22a391eb2b429d339bc9c0a5b473431c

**Comment by danischm** [comment]
everything resolved now?
