### ISSUE TITLE
Missing Paramters for sdwan_cisco_secure_internet_gateway_feature_template

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#161]
The following parameters are missing.

1. zscaler_surrogate_refresh_time under https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/cisco_secure_internet_gateway_feature_template

2. interval and interval_variable under https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/cisco_secure_internet_gateway_feature_template#nested-schema-for-trackers

3. tracker and tracker_variable under https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/cisco_secure_internet_gateway_feature_template#nested-schema-for-interfaces

**Comment by rrahimm** [comment]
interval and interval_variable

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/d9b2148e-7f4b-4116-a822-e0b53634bb27)

**Comment by rrahimm** [comment]
tracker and tracker_variable

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/020cad9e-1fd5-4501-9cc8-a3d37d078bfc)

**Comment by rrahimm** [comment]
zscaler_surrogate_refresh_time 

you will see it after enabling "Authentication Required" in Advanced Settings

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/d8cb894e-b828-4dc3-915e-d8c3eebbb389)

**Comment by danischm** [comment]
The `tracker` attribute under `interfaces` does not seem to support a variable (also in the UI).

**Comment by danischm** [comment]
Added in v0.3.7 release.
