### ISSUE TITLE
SIG credentials template

### ISSUE THREAD

**Issue by juchowan** [CiscoDevNet/terraform-provider-sdwan#162]
SIG credentials template template should only have either zscaler or umbrella settings. Currently for zscaler which fails:

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/406f4a49-ec9e-443a-bd9a-fa10a16bf59b)

Should be for zscaler:
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/f9a82a0b-534b-4d88-bb8e-55daeaaf8e3b)

Should be for umbrella:
![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/955fd32d-b8af-4405-8ca9-d2d5cc9b1e1a)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/664256a8a71d207280b938f391269eebb192fbfb
