### ISSUE TITLE
SIG credentials template isGlobal missing

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#163]
When you create SIG creds template in UI, the JSON contains "isGlobal: true". 
<img width="719" alt="Screenshot 2024-01-30 at 15 09 50" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/92273798/ff292b0e-0183-4f1b-a9f5-0966931c4dcf">

However when template is created using terraform, this option is missing:
<img width="718" alt="Screenshot 2024-01-30 at 15 08 39" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/92273798/59f19843-391b-45d4-8675-f0c6601c095e">

Without this option set, when creating secure internet gateway interface template, the vManage will block user saying the credentials template is missing. We should always set "isGlobal: true" when creating sig creds template.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/29610ad37688d57b722869398b29926afc1ae020

**Comment by danischm** [comment]
Fixed in v0.3.6 release.
