### ISSUE TITLE
Secure Internet Gateway templates missing some keys

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#164]
When you configure secure internet gateway template in UI, the generated JSON has vpn-id section, whereas the terraform generated template is missing this. This is smth static, not configurable in UI, but should be in the definition:
```
...
  "templateDefinition": {
...
    "vpn-id": {
      "vipObjectType": "object",
      "vipType": "constant",
      "vipValue": 0
    },
    "interface": {
...
```

**Comment by tzarski0** [comment]
When you configure secure internet gateway template in UI, the generated JSON has priority-order section under ha-pair, whereas the terraform generated template is missing this. Example from UI generate template:
<img width="643" alt="Screenshot 2024-01-30 at 16 09 05" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/92273798/0f2fd8d6-2a11-49d3-9d82-b8e6afe7e4a6">

**Comment by tzarski0** [comment]
When you configure secure internet gateway template in UI, the generated JSON has interface ip unnumbered section, whereas the terraform generated template is using ip address ignore. Example from UI generate template:
<img width="633" alt="Screenshot 2024-01-30 at 16 13 07" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/92273798/e0d5c279-d97d-4e94-ab15-5812dfe0de1b">

**Comment by danischm** [comment]
> When you configure secure internet gateway template in UI, the generated JSON has vpn-id section, whereas the terraform generated template is missing this. This is smth static, not configurable in UI, but should be in the definition:

The resource has this attribute (https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/cisco_secure_internet_gateway_feature_template#vpn_id). Is that not what you are referring to?

**Comment by danischm** [comment]
> When you configure secure internet gateway template in UI, the generated JSON has priority-order section under ha-pair, whereas the terraform generated template is missing this. Example from UI generate template:

Does this make a difference? I have seen a few occasions where some extra information was not required to be included in the payload and it did not seem to make a difference.

**Comment by danischm** [comment]
> When you configure secure internet gateway template in UI, the generated JSON has interface ip unnumbered section, whereas the terraform generated template is using ip address ignore. Example from UI generate template:

https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/3c59f03cbc02292bfde00dc07ebc7c06dd20c5f8

**Comment by danischm** [comment]
Please let me know if there is anything missing in the latest release (v0.3.6).

**Comment by juchowan** [comment]
> > When you configure secure internet gateway template in UI, the generated JSON has priority-order section under ha-pair, whereas the terraform generated template is missing this. Example from UI generate template:
> 
> Does this make a difference? I have seen a few occasions where some extra information was not required to be included in the payload and it did not seem to make a difference.

this is not generated now and seems to be working, but if i save that template manually from gui it will be generated then - is this going to be a problem?

**Comment by juchowan** [comment]
for trackers we are missing interval attribute (same as multiplier)

**Comment by juchowan** [comment]
missing possibility to configure tracker under interface:

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/79261946/92b64401-2913-4b9a-92da-9adc4701781d)

**Comment by danischm** [comment]
> this is not generated now and seems to be working, but if i save that template manually from gui it will be generated then - is this going to be a problem?

It shouldn't. Any extra information should not hurt.

**Comment by danischm** [comment]
> missing possibility to configure tracker under interface

should be added here: https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/e432f7182398c01ce6b0dbf32508a91c178c909b

**Comment by danischm** [comment]
> for trackers we are missing interval attribute (same as multiplier)

Added here: https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/e432f7182398c01ce6b0dbf32508a91c178c909b
