### ISSUE TITLE
Terraform destroy fails when devices are attached to templates.

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#166]
When I deploy/apply configuration, it works. But when I do destroy later, TF should start with detaching template, but it tries right away to remove device template and fails as it's attached:
```
│ Error: Client Error
│ 
│ Failed to delete object (DELETE), got error: HTTP Request failed: StatusCode 400,
│ {"error":{"type":"error","message":"Failed to delete template.","details":"Template is attached to
│ devices","code":"MTEMP0007"}} 
```
When we do TF apply we first create device templates then we attach them.
When we do TF destroy, the logic should be first to detach and then delete device templates.

**Comment by tzarski0** [comment]
With the most recent provider/modules version I no longer see this problem. It could have been related to other problem that was fixed in the meantime. Should we close this?

**Comment by danischm** [comment]
Yes, let's close it for now and we can always re-open if it pops up again.
