### ISSUE TITLE
Feature request | VPN Interface Cellular

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#167]
We would like to enable the following Feature Template support on Provider.

**VPN Interface Cellular**

GUI Path >> Feature Template >> Add Template >> VPN Interface Cellular

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/pull/181

**Comment by danischm** [comment]
Added in v0.3.7 release.
