### ISSUE TITLE
Feature Request | VPN Interface DSL PPPoA

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#168]
We would like to enable the following Feature Template support on Provider.

**VPN Interface DSL PPPoA**

GUI Path >> Feature Template >> Add Template >> VPN Interface DSL PPPoA

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/pull/181

**Comment by danischm** [comment]
Added in v0.3.7 release.
