### ISSUE TITLE
sdwan_feature_device_template | general_templates list issue 

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#171]
We found a strange issue with the resource "sdwan_feature_device_template"

when we build the general templates, it is a combination of different types and it's sub-templates.

When doing this for vpn_service_template with type "cisco_vpn", we see the below error.

**│ The true and false result expressions must have consistent types. The 'true' tuple has length 0, but the 'false' tuple has length 2.** 

on further troubleshooting, we found that the true and false conditions were expecting the same number of lists. for example, False condition would get a simple [] and true may be [] [] [].

Below is the line of Terraform module where we saw this error and currently handling it with a workaround.

https://github.com/netascode/terraform-sdwan-nac-sdwan/blob/main/sdwan_device_templates.tf

Non-working
```yaml
    try(each.value.vpn_service_templates, null) == null ? [] : [for st in try(each.value.vpn_service_templates, []) : {
```
Working (workaround)
```yaml
    try(each.value.vpn_service_templates, null) == null ? try([for ss in try(each.value.vpn_service_templates, []) : null], []) : [for st in try(each.value.vpn_service_templates, []) : {
```

**Comment by danischm** [comment]
This is an issue with the mentioned expression/module not the provider itself.

**Comment by rrahimm** [comment]
as this is not an issue to be fixed by the provider. Leaving the module in its current working condition.
