### ISSUE TITLE
[UX2.0] Feature Profiles/Parcels description field should be optional

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#187]
In SD-WAN Manager: feature profiles and parcels name is mandatory and description is optional.
In SD-WAN TF provider both fields are mandatory. Ask is to make description field optional for all feature profiles and parcels.

**Comment by seconroy** [comment]
[[UX2.0] Increase minimum version and resolve issues](https://github.com/CiscoDevNet/terraform-provider-sdwan/pull/190) - Will be implemented in the 0.3.7 release

**Comment by tzarski0** [comment]
@seconroy I've tested that on local installation using latest code from repository. It seems parcel description is now optional (correct), but feature profile description is still mandatory (wrong). If I try to configure feature profile without description, it fails with:
```
Error: Missing Configuration for Required Attribute
```

Could you please fix that too for feature profiles?

**Comment by tzarski0** [comment]
verified
Feature parcel description is optional. Feature profile description is mandatory and if user doesn't want to use it, it should set it to empty string (same as API does it).
