### ISSUE TITLE
[UX2.0] In profile parcels, the feature_profile_id should be mandatory

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#188]
feature_profile_id field is now optional for profile parcels. If you try to configure parcel without feature_profile_id, the API will fail, so we should put this field as mandatory.

**Comment by seconroy** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/pull/190 - Will be implemented in the 0.3.7 release

**Comment by danischm** [comment]
Fixed in v0.3.7 release.
