### ISSUE TITLE
[UX2.0] Fix typos in sdwan_system_omp_profile_parcel

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#189]
- change "advertise_ipv4_cpnnected" to "advertise_ipv4_connected"
- change "advertise_ipv4_cpnnected_variable" to "advertise_ipv4_connected_variable"

**Comment by seconroy** [comment]
[[UX2.0] Increase minimum version and resolve issues](https://github.com/CiscoDevNet/terraform-provider-sdwan/pull/190) - Will be fixed in the 0.3.7 release

**Comment by danischm** [comment]
Fixed in v0.3.7 release.
