### ISSUE TITLE
in vpn interface template, dhcp must set to null when use static IP, false would still enable dhcp

### ISSUE THREAD

**Issue by wcmder** [CiscoDevNet/terraform-provider-sdwan#197]
the vpn interface template looks like at the GUI, but when attached, static assignment is missing and dhcp enabled.

**Comment by wcmder** [comment]
this is interface config, when assigned values at the variables in  sdwan_attach_feature_device_template, attached to device, I would loss the control connection then the device would fallback to previous configuration after 6 minutes 
<img width="529" alt="Screenshot 2024-04-17 at 3 30 25 PM" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/114770193/1083c95e-549d-48c4-8afc-388a4079f937">

I did a manual attach at GUI and see the DIFF - so I changed the dhcp default false to null to solve this
<img width="1189" alt="Screenshot 2024-04-15 at 9 03 03 PM" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/114770193/c2e156ed-1bbf-41f2-8adc-e7aa7a6b7e32">

**Comment by danischm** [comment]
Can you confirm that it works if you set DHCP to "null" instead of "false"? There is a known issue where vManage does not interpret a boolean value of "false" correctly, therefore the workaround for now is to use "null".
