### ISSUE TITLE
in vpn tempalte, optional static IP route has this error when the variable assignment is not given or set to null.

### ISSUE THREAD

**Issue by wcmder** [CiscoDevNet/terraform-provider-sdwan#198]
Failed to attach device template, got error: Action
│ push_feature_template_configuration-dc12dea0-0acf-4311-badf-cc613620803a for device
│ C8K-DA78106D-B07B-F863-DB2B-B3499A0FEC5A failed. Activity log: ["[16-Apr-2024 18:58:36 UTC] Configuring device with
│ feature template: tf_c8kv_type1","[16-Apr-2024 18:58:36 UTC] Failed to update configuration - Error  invalid value
│ for: prefix in /templates/template/vpn/vpn-instance/ip/route/prefix\n"]

**Comment by danischm** [comment]
Thanks for opening the issue! Could you share an example resource config to recreate the issue?

**Comment by wcmder** [comment]
I just figured this out - optional variable must be set to "TEMPLATE_IGNORE" if not used
<img width="557" alt="Screenshot 2024-04-17 at 3 47 16 PM" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/114770193/7009119a-4769-42c7-b5be-66b3296e4380">
