### ISSUE TITLE
address_families under bgp template doesn't work

### ISSUE THREAD

**Issue by wcmder** [CiscoDevNet/terraform-provider-sdwan#203]
```
module "bgp_template1" {
  name        = "tf_vpn1_bgp"
  description = "tf_vpn1_bgp"
  source      = "../modules/sdwan/features/bgp"

  as_number_variable = "vpn1_bgp_asn" ###

  /* THIS SECTION DO NOT WORK
  address_families = [
    {
      family_type = "ipv4-unicast"
      default_information_originate_variable = "vpn1_bgp_default_originate"

      redistribute_routes = [
        {
          optional          = true
          protocol_variable = "vpn1_bgp_redis_proto1"
        },
        {
          optional          = true
          protocol_variable = "vpn1_bgp_redis_proto2"
        }
      ]
     
    }
  ]
   */
   ```

**Comment by danischm** [comment]
This seems to be a custom module you are using here. Could you share an example resource config to recreate the issue?

**Comment by wcmder** [comment]
the address_families block was commented out, removed the /*  */, terraform apply see no changes -
<img width="1124" alt="Screenshot 2024-04-17 at 4 05 24 PM" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/114770193/15517816-0a74-4a45-b8c0-21a1dcd609fa">

**Comment by danischm** [comment]
This code refers to a custom module not a provider resource. Please try to recreate the issue with a resource config and share the config here. Thanks a lot!

**Comment by wcmder** [comment]
I tested the resource rather than module, and it worked, found the issue in my module, thanks.

**Comment by wcmder** [comment]
not an issue
