### ISSUE TITLE
[UX2.0] resource_sdwan_system_mrf_profile_parcel should have enable_migration_to_mrf and migration_bgp_community as optional

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#209]
Right now in resource resource_sdwan_system_mrf_profile_parcel, the enable_migration_to_mrf and migration_bgp_community are required, but should be optional.

**Comment by tzarski0** [comment]
This got broken by commit 158ab45

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/af3abc921ba94cbb6a325f53415e869b2412d32f

**Comment by tzarski0** [comment]
Fixed in v0.3.8 release.
