### ISSUE TITLE
Add terraform import functionality to the "sdwan_attach_feature_device_template" resource

### ISSUE THREAD

**Issue by cmohorea** [CiscoDevNet/terraform-provider-sdwan#232]
Suggestion:
Add importing functionality to the sdwan_attach_feature_device_template by retrieving variable values and adding then to the state. 
It is a part of the process anyway when adding/changing variable later on.

Otherwise, in a current model, in brownfield, even if you have a config and you manually defined all the values, 1st "terraform apply" is a change, even if TF config is same as real (and potentially dangerous as we don't know if we matched values correctly or missed something)

**Comment by seconroy** [comment]
Released in v0.5.0.
