### ISSUE TITLE
[UX2.0] transport_management_vpn_interface_ethernet_profile_parcel missing option to set ipv4/6_address as dynamic.

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#269]
In transport_management_vpn_interface_ethernet_profile_parcel, we have option to set static ip with ipv4_address parameter, but I don't see any option to set ip address as dynamic. Am I missing something or do we need to add that?

**Comment by seconroy** [comment]
if you configure `ipv4_dhcp_distance` the ip address should be set as dynamic

**Comment by tzarski0** [comment]
In sdwan_cisco_vpn_interface_feature_template, we've had "dhcp" bool variable that was allowing that. Maybe we should do it in similar way here?

**Comment by seconroy** [comment]
In sdwan_cisco_vpn_interface_feature_template the "dhcp" bool variable was needed by the API and in transport_management_vpn_interface_ethernet_profile_parcel there doesn't seem to be anything similar in the scheme/API. I will have a look and see how this can be improved though

**Comment by tzarski0** [comment]
@seconroy it seems like we have same problem with sdwan_transport_wan_vpn_interface_ethernet_profile_parcel

**Comment by tzarski0** [comment]
Resolved in release 0.5.1
