### ISSUE TITLE
[UX2.0] transport_management_vpn_interface_ethernet_profile_parcel basic_configuration_description should be renamed to interface_description

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#270]
In transport_management_vpn_interface_ethernet_profile_parcel, we have "basic_configuration_description" parameter which name is hard to decode. Wouldn't it be better if we just name it "interface_description"? Or is that somehow autogenerated?

**Comment by seconroy** [comment]
We tried to keep the name inline with the UI but this can be changed if it is hard to understand. It is the same in transport_management_vpn

**Comment by tzarski0** [comment]
Verified and will be fixed in 0.3.10.
