### ISSUE TITLE
sdwan_zone_based_fw_policy_definition (Resource) | Missing destination_fqdn

### ISSUE THREAD

**Issue by rsoniya077** [CiscoDevNet/terraform-provider-sdwan#277]
We are unable to create destination_fqdn module. In [Nested Schema for rules.match_entries](https://github.com/seconroy/terraform-provider-sdwan/blob/779c0068daa92a2fc2c38ea2b601a5ded3f7b258/docs/resources/zone_based_fw_policy_definition.md#nested-schema-for-rulesmatch_entries) There is no destination_fqdn.

Example data:
[Nested Schema for rules.match_entries](https://github.com/seconroy/terraform-provider-sdwan/blob/779c0068daa92a2fc2c38ea2b601a5ded3f7b258/docs/resources/zone_based_fw_policy_definition.md#nested-schema-for-rulesmatch_entries)
Required:
•	type (String) Type of match entry
o	Choices: sourceFqdnList, sourceDataPrefixList, sourceGeoLocationList, sourcePortList, destinationFqdnList, destinationDataPrefixList, destinationGeoLocationList, destinationPortList, appList, protocolNameList, sourceIp, sourcePort, sourceFqdn, destinationIp, destinationPort, sourceGeoLocation, destinationGeoLocation, protocolName, protocol, app, ruleSetList
Note: We need to add  destination_fqdn in [Nested Schema for rules.match_entries](https://github.com/seconroy/terraform-provider-sdwan/blob/779c0068daa92a2fc2c38ea2b601a5ded3f7b258/docs/resources/zone_based_fw_policy_definition.md#nested-schema-for-rulesmatch_entries)

While creating the [sdwan_zone_based_fw_policy_definition](https://github.com/seconroy/terraform-provider-sdwan/blob/779c0068daa92a2fc2c38ea2b601a5ded3f7b258/docs/resources/zone_based_fw_policy_definition.md) module we are getting error.

Error:

│ Attribute rules[1].match_entries[2].type value must be one of: ["sourceFqdnList" "sourceDataPrefixList" "sourceGeoLocationList" "sourcePortList"  
│ "destinationFqdnList" "destinationDataPrefixList" "destinationGeoLocationList" "destinationPortList" "appList" "protocolNameList" "sourceIp"      
│ "sourcePort" "sourceFqdn" "destinationIp" "destinationPort" "sourceGeoLocation" "destinationGeoLocation" "protocolName" "protocol" "app"
│ "ruleSetList"], got: "destinationFqdn"

Refer: [We are unable to create destination fqdn.docx](https://github.com/user-attachments/files/15926228/We.are.unable.to.create.destination.fqdn.docx)

**Comment by danischm** [comment]
Fixed in v0.3.10.
