### ISSUE TITLE
sdwan_zone_based_firewall_policy_definition | match_entries should be optional

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#278]
The [match_entries](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/zone_based_firewall_policy_definition#match_entries) in [Nested Schema for rules](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/zone_based_firewall_policy_definition#nested-schema-for-rules) should be optional. It is now a required variable currently.

Reference:

![image](https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/3b7756f7-71d2-4000-8622-8422a02dbdd6)

**Comment by danischm** [comment]
Released in v0.3.12.
