### ISSUE TITLE
In sdwan_traffic_data_policy_definition, loss_correction_fec_threshold should be set to str in JSON payload, not int

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#288]
In sdwan_traffic_data_policy_definition, when you configure the loss_correction_fec_threshold, terraform pushes:
<img width="250" alt="Screenshot 2024-07-11 at 18 02 20" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/92273798/d64e38df-0908-485b-b0c1-b50df50c7be5">

The correct configuration should be:
<img width="297" alt="Screenshot 2024-07-11 at 18 03 23" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/92273798/d57e6050-a837-4c45-9eb1-563ef65ef966">

So we should translate the int input from TF resource to string in JSON.

**Comment by rrahimm** [comment]
@tzarski0 

it's strange, this worked in 20.9

**Comment by tzarski0** [comment]
In my test it worked. However if you:
1. Do TF apply -> it works.
2. Go to UI click Edit and Save right away.
3. Do TF plan -> it will show the diff, although you didn't change anything in step 2.

**Comment by tzarski0** [comment]
Validated and will come in v0.3.14
