### ISSUE TITLE
Failure_mode should be used only when IPS is enabled | sdwan_security_policy

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#289]
in sdwan_security_policy, we see that the "failure_mode" is set to open even when the definitions doesn't have type "intrusionPrevention" added.

This is causing the policy attachment to fail with 400 error.

https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/security_policy#failure_mode

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/0da9e7be98dbb908750b76623e11bfedcd72ebfc

**Comment by danischm** [comment]
Released in v0.3.13.
