### ISSUE TITLE
Fix for sdwan_security_policy destroy

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#290]
We are seeing an issue where we are unable to delete the "sdwan_zone_based_firewall_policy_definition" and "sdwan_intrusion_prevention_policy_definition" etc. after the "sdwan_security_policy" has been deleted.

the definitions still hold a reference to the deleted policy and doesn't allow to be deleted.

we are looking for a similar fix as already done for [Add workaround for concurrent deletion of localized policies
](https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/b63e740c7bbef9b354d3ebfe965160ec806cf501)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/76379f8922adf659d1945d6fb403347fd539eb77

**Comment by danischm** [comment]
Released in v0.3.13.
