### ISSUE TITLE
[UX2.0] sdwan_transport_wan_vpn_feature appears to fail with IPv4 static route with address variable in next hop.

### ISSUE THREAD

**Issue by rsaville2** [CiscoDevNet/terraform-provider-sdwan#341]
If you configure sdwan_transport_wan_vpn_feature with an ipv4 static route, the next_hops list appears to take address but not address_variable:

`resource "sdwan_transport_wan_vpn_feature" "medium_transport_wan_vpn_feature" {
  name                       = "medium_transport_wan_vpn_feature"
  description                = "Medium-Sized Branch Transport WAN VPN Feature.  Managed by Terraform"
  feature_profile_id         = sdwan_transport_feature_profile.medium_branch_transport_profile.id
  vpn                        = 0
  ipv4_static_routes = [
    {
      network_address = "0.0.0.0"
      subnet_mask     = "0.0.0.0"
      gateway         = "nextHop"
      next_hops = [
        {
          address_variable = "nhaddr0"
          administrative_distance = 1
        }
      ]
      administrative_distance = 1
    }
  ]
}`

It fails with:

`│ Error: Client Error
│
│   with sdwan_transport_wan_vpn_feature.medium_transport_wan_vpn_feature,
│   on main.tf line 193, in resource "sdwan_transport_wan_vpn_feature" "medium_transport_wan_vpn_feature":
│  193: resource "sdwan_transport_wan_vpn_feature" "medium_transport_wan_vpn_feature" {
│
│ Failed to configure object (POST), got error: HTTP Request failed: StatusCode 400,
│ {"error":{"message":"Invalid Json Payload Input","code":"SCHVALID0001","details":"{\"Validation
│ Errors\":{\"Invalid Format Attributes\":[\"data.ipv4Route[0].nextHop[0].address\"]}}","type":"error"}}`

Documentation shows the address_variable as a string.  Is this correct?

**Comment by rsaville2** [comment]
My apologies, formatting issues with the code block.   

resource "sdwan_transport_wan_vpn_feature" "medium_transport_wan_vpn_feature" {
  name                       = "medium_transport_wan_vpn_feature"
  description                = "Medium-Sized Branch Transport WAN VPN Feature.  Managed by Terraform"
  feature_profile_id         = sdwan_transport_feature_profile.medium_branch_transport_profile.id
  vpn                        = 0
  ipv4_static_routes = [
    {
      network_address = "0.0.0.0"
      subnet_mask     = "0.0.0.0"
      gateway         = "nextHop"
      next_hops = [
        {
          address_variable = "nhaddr0"
          administrative_distance = 1
        }
      ]
      administrative_distance = 1
    }
  ]
}

Error: Client Error

with sdwan_transport_wan_vpn_feature.medium_transport_wan_vpn_feature,
on main.tf line 193, in resource "sdwan_transport_wan_vpn_feature" "medium_transport_wan_vpn_feature":
193: resource "sdwan_transport_wan_vpn_feature" "medium_transport_wan_vpn_feature" {

Failed to configure object (POST), got error: HTTP Request failed: StatusCode 400,
{"error":{"message":"Invalid Json Payload Input","code":"SCHVALID0001","details":"{\"Validation
 Errors\":{\"Invalid Format Attributes\":[\"data.ipv4Route[0].nextHop[0].address\"]}}","type":"error"}}

**Comment by seconroy** [comment]
Thank you for opening the issue, Currently variables within features need to be wrapped in `{{}}`.
```
resource "sdwan_transport_wan_vpn_feature" "medium_transport_wan_vpn_feature" {
  name = "medium_transport_wan_vpn_feature"
  description = "Medium-Sized Branch Transport WAN VPN Feature. Managed by Terraform"
  feature_profile_id = sdwan_transport_feature_profile.medium_branch_transport_profile.id
  vpn = 0
  ipv4_static_routes = [
    {
    network_address = "0.0.0.0"
    subnet_mask = "0.0.0.0"
    gateway = "nextHop"
    next_hops = [
      {
        address_variable = "{{nhaddr0}}"
        administrative_distance = 1
      }
    ]
    administrative_distance = 1
    }
  ]
}
```

**Comment by rsaville2** [comment]
Thanks for the quick response clarifying that.  It works fine.  Closing this issue.
