### ISSUE TITLE
Incorrectly set mandatory fields blocking use of resource

### ISSUE THREAD

**Issue by benkelly12** [CiscoDevNet/terraform-provider-sdwan#344]
the following fields are incorrectly set as mandatory, this is preventing me from using this resource
"ipv4_address"
"ipv4_subnet_mask"

These are not required if you are using 
ipv4_address_variable
 ipv4_subnet_mask_variable

resource "sdwan_service_lan_vpn_interface_svi_feature" "service_svi" {
  for_each                   = local.vpn-subnets_loop
  name                       = "vpn ${each.value.vpn_name} ${each.value.subnet_name} subnet"
  description                = "vpn ${each.value.vpn_name} ${each.value.subnet_name} subnet"
  feature_profile_id         = each.value.feature_profile_id
  service_lan_vpn_feature_id = each.value.service_lan_vpn_feature_id
  shutdown                   = false
  interface_name             = "Vlan${each.value.vlan_number}"
  interface_description      = "vpn ${each.value.vpn_name} ${each.value.subnet_name} subnet"
  interface_mtu              = 1500
  ip_mtu                     = 1500
  ipv4_address_variable      = "{{vpn-${each.value.vpn_name}_vlan-${each.value.subnet_name}_ip"
  ipv4_subnet_mask_variable  = "{{vpn-${each.value.vpn_name}_vlan-${each.value.subnet_name}_mask"

  ipv4_dhcp_helpers = each.value.dhcp_helpers

**Comment by seconroy** [comment]
Thank you for opening the issue, This has already been fixed and will be included in the next release.

**Comment by seconroy** [comment]
At the moment we don't have a specific date for the next release,
We are still developing some features that we want to include in 0.4.2

**Comment by seconroy** [comment]
Released in v0.5.0.
