### ISSUE TITLE
Import on activate centralized policy not supported

### ISSUE THREAD

**Issue by vjoshevs** [CiscoDevNet/terraform-provider-sdwan#347]
Today according to the documentation import for centralized policy is not enabled 

https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/activate_centralized_policy

when trying to use the latest SDWAN TF provider 0.4.1 getting error:

    "Error: Resource Import Not Implemented
    This resource does not support import. Please contact the provider developer for additional information."

Command trying to do:
```
terraform import sdwan_activate_centralized_policy.example "f6b2c44c-693c-4763-b010-895aa3d236bd"
```

**Comment by seconroy** [comment]
Released in v0.5.0.
