### ISSUE TITLE
Import attach_feature_device_template not supported

### ISSUE THREAD

**Issue by vjoshevs** [CiscoDevNet/terraform-provider-sdwan#348]
Today according to the documentation import for attach feature device template is not enabled.

https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/attach_feature_device_template 

when trying to use the latest SDWAN TF provider 0.4.1 getting error:

```
Error: Resource Import Not Implemented
 
This resource does not support import. Please contact the provider developer for additional information.
```

Command trying to do:
```
terraform import sdwan_attach_feature_device_template.example  "C8K-A24A2A22-AAAA-2222-A2A2-A11119AAAC1A"
```

**Comment by seconroy** [comment]
Released in v0.5.0.
