### ISSUE TITLE
Deletion of security policy might fail due to references

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#353]
Removing security policy or its objects might fail due to broken references, for example:
```
[2024-10-21T08:25:43.872Z] Failed to delete object (DELETE), got error: HTTP Request failed: StatusCode
[2024-10-21T08:25:43.872Z] 400, {"error":{"type":"error","message":"Policy delete
[2024-10-21T08:25:43.872Z] failed","details":"Policy SECURITY-POLICY-TEMPLATE-02 is attached to
[2024-10-21T08:25:43.872Z] device","code":"POLICY0005"}}
```

In the past, we've implemented the following fixes for this issue for localized policy:
- concurent deletion fix: https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/b63e740c7bbef9b354d3ebfe965160ec806cf501
- references fix: https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/928b7a483105c1e5a29daf5a8aa01f7dff01f94e

For security policy, I see:
- we implemented concurent deletion fix: https://github.com/CiscoDevNet/terraform-provider-sdwan/commit/76379f8922adf659d1945d6fb403347fd539eb77
- we are missing the references fix

Ask is to create same references fix for security policy (/dataservice/template/policy/security/) and its objects (/dataservice/template/policy/definition/<object-name>).

**Comment by seconroy** [comment]
Released in v0.5.0.
