### ISSUE TITLE
missing version for sdwan_security_policy definitions

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#358]
the [definitions of sdwan_security_policy](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/security_policy#nested-schema-for-definitions) should also support version to be able to catch/identify changes down the tree whenever the mapped definitions undergo a change.

**Comment by rrahimm** [comment]
@seconroy  / @danischm 

Request your help for a quick fix on this one

**Comment by seconroy** [comment]
Released in v0.5.0.
