### ISSUE TITLE
[UX2.0] access-lists are not accepting port ranges

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/terraform-provider-sdwan#364]
In the UX2.0 ACL (e.g. sdwan_transport_ipv4_acl_feature), the resource accepts the port as integer (e.g. "10"), but does not accept the port range (e.g. "10-20"). Ask is to add support for port range to every UX2.0 ACL for source and destination ports.

**Comment by seconroy** [comment]
Resolved in release 0.5.1
