### ISSUE TITLE
Common Argument Reference - device_type - c8000v missing

### ISSUE THREAD

**Issue by srigel** [CiscoDevNet/terraform-provider-sdwan#60]
Hi!
The "device_type" c8000v is missing in the terraform provider, it is not supported yet? Can you update the link (https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/device_template) when its supported please?

Regards,

**Comment by danischm** [comment]
Fixed in revamped 0.2.0 release.
